gitRepoUrl = "https://github.com/yTrev/Replion"

[[classOrder]]
section = "Server"
classes = ["Server", "ServerReplion"]

[[classOrder]]
section = "Client"
classes = ["Client", "ClientReplion"]

[docusaurus]
favicon = "/img/favicon.ico"

[navbar]
title = ""

[navbar.logo]
alt = "Replion"
src = "/img/logo.svg"
