[package]
name = "ytrev/replion"
description = "A lightweight State Replicator."
version = "2.0.0-rc.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["yTrev"]
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "default.project.json"]

[dependencies]
Signal = "sleitnick/signal@1.5.0"
Freeze = "duckarmor/freeze@0.1.4"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"